apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ashmehroz1/gitops-demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              value: "http://backend.default.svc.cluster.local:8080"
